### ISSUE TITLE
System.InvalidOperationException:“The control Lemon.ModuleNavigation.Sample.ModuleAs.ViewA (Content = StackPanel) already has a visual parent ContentPresenter (Name = PART_ContentPresenter, Host = Lemon.ModuleNavigation.Avaloniaui.Containers.NContainer) while trying to add it as a child of ContentPresenter (Name = PART_ContentPresenter, Host = Lemon.ModuleNavigation.Avaloniaui.Containers.NContainer).”

### ISSUE THREAD

**Issue by Ming-jiayou** [NeverMorewd/Lemon.ModuleNavigation#11]
When I start the latest code, this error occurs:
![image](https://github.com/user-attachments/assets/b73fa4b0-3a74-4e54-aa3f-a7598ea2f0e7)
May I ask how to fix it?

**Comment by NeverMorewd** [comment]
Pull latest code and try please

**Comment by NeverMorewd** [comment]
New commit:
https://github.com/NeverMorewd/Lemon.ModuleNavigation/commit/980ed2bd39041c371d87eab7662795d7c74f944c

**Comment by Ming-jiayou** [comment]
Thank you, it's okay now.
