### ISSUE TITLE
 After using Lemon.ModuleNavigation, Avalonia does not have a preview function

### ISSUE THREAD

**Issue by lixiaoxiang1369** [NeverMorewd/Lemon.ModuleNavigation#3]
After using Lemon.ModuleNavigation, Avaloina does not have a preview function and prompts: Process Exited, The previewer process exited unexpectedly. See the output window for more information.

**Comment by NeverMorewd** [comment]
https://github.com/AvaloniaUI/Avalonia/discussions/13743

I will apply this workaround to `Lemon.ModuleNavigation.Avaloniaui.Sample`

**Comment by NeverMorewd** [comment]
Fixed
https://github.com/NeverMorewd/Lemon.ModuleNavigation/pull/4

**Comment by lixiaoxiang1369** [comment]
Thank you
