### ISSUE TITLE
How to use ViewA and ViewModelA in ModulaA

### ISSUE THREAD

**Issue by lixiaoxiang1369** [NeverMorewd/Lemon.ModuleNavigation#6]
I want to use the splitview navigation window to display the content of Module A. My code is attached, please help me take a look. Thank you.
[Advantech.IIoTDAQ.zip](https://github.com/user-attachments/files/17371775/Advantech.IIoTDAQ.zip)

**Comment by NeverMorewd** [comment]
见附件：
[Advantech.IIoTDAQ.new.zip](https://github.com/user-attachments/files/17372089/Advantech.IIoTDAQ.new.zip)
主要改动点：
注意，导航的目标是模块、不是viewmodel或者view。ListItemTemplate中一定要有module的信息
![image](https://github.com/user-attachments/assets/5470f032-50db-47cc-98bf-5b3eae9e2589)

**Comment by lixiaoxiang1369** [comment]
好的，谢谢。

**Comment by lixiaoxiang1369** [comment]
您好，我想再请教一个小问题，如何在程序启动时直接加载ViewA的页面，谢谢。

**Comment by NeverMorewd** [comment]
LoadOnDemand 设置为False，默认值就是False，你可能给override了
```
public class ModuleA : AvaModule<ViewA, ViewModelA>
{
        public ModuleA(IServiceProvider serviceProvider) : base(serviceProvider)
        {

        }

        /// <summary>
        /// Specifies whether this module needs to be loaded on demand
        /// 指定该模块是否按需加载
        /// Default value is True
        /// </summary>
        public override bool LoadOnDemand => false;

}
```

**Comment by lixiaoxiang1369** [comment]
您可能没有明白我的意思，程序启动时没有显示页面，只能单击左边的按钮之后才能可以显示，能否在程序启动时自动显示ViewA的画面，谢谢。
[反应的问题.zip](https://github.com/user-attachments/files/17427398/default.zip)

**Comment by NeverMorewd** [comment]
因为你的module是 通过selecteditem来导航的，只有selectedItem变化了才能触发导航。
你在启动时 设置下selecteditem 就可以了。也可以在listbox直接设置 selectedindex = 0

**Comment by lixiaoxiang1369** [comment]
以上两种方法还不行，我再看一下，辛苦了，谢谢，打扰了。

**Comment by NeverMorewd** [comment]
![image](https://github.com/user-attachments/assets/97ac88c6-2baf-4825-b1b6-6be4193f6ee4)
我试了selectedindex 也不行、用代码直接设置是可以的

**Comment by lixiaoxiang1369** [comment]
感谢，感谢，可以了。
